---
- name: Ensure configs directory exists
  ansible.builtin.file:
    path: "{{ openvpn_configs_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Render nginx config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx-file-browser.conf
    mode: '0644'
  register: nginx_config

- name: Pull nginx Docker image
  community.docker.docker_image:
    name: "{{ nginx_image }}"
    source: pull
    state: present

- name: Run nginx container
  community.docker.docker_container:
    name: "{{ nginx_container_name }}"
    image: "{{ nginx_image }}"
    state: started
    restart_policy: always
    published_ports:
      - "{{ nginx_host_port }}:80"
    volumes:
      - "/etc/nginx-file-browser.conf:/etc/nginx/conf.d/default.conf:ro"
      - "{{ openvpn_configs_dir }}:{{ nginx_container_root }}/{{ nginx_index_subdir }}:ro"
    restart: "{{ nginx_config.changed }}"

